name: Docker Image CI-LinkWarden

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        # build with env file
        run: docker build -t ${{secrets.DOCKER_REGISTRY}}/${{secrets.DOCKER_USERNAME}}/linkwarden:latest -f Dockerfile --build-arg NEXT_TELEMETRY_DISABLED=1 --build-arg POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}} --build-arg NEXTAUTH_URL=${{secrets.NEXTAUTH_URL}} --build-arg NEXTAUTH_SECRET=${{secrets.NEXTAUTH_SECRET}} .
      - name: Log in to Docker registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} ${{secrets.DOCKER_REGISTRY}}

      - name: Push the Docker image
        run: docker push ${{secrets.DOCKER_REGISTRY}}/${{secrets.DOCKER_USERNAME}}/linkwarden:latest